const number =[2,3,4];
console.log(number);
number.push(1);
console.log(number);
number.push=333;
console.log(number);
number.unshift(1111);
console.log(number);
number.unshift=22222;
console.log(number);
number.splice(1,0,"Naser");
console.log(number);
number.splice(1,1,"reyhaneh");
console.log(number);